version: 2

updates:
  # Root-level configuration for pnpm workspace
  # This manages all dependencies across the entire monorepo
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: daily
      time: '09:00'
    labels:
      - 'dependabot'
      - 'dependencies'
      - 'monorepo'
    commit-message:
      include: scope
      prefix: 'chore'
    open-pull-requests-limit: 20
    groups:
      # Monorepo and build tools
      monorepo-tools:
        patterns:
          - 'turbo'
          - '@turbo/*'
          - 'pnpm'
          - 'concurrently'

      # TypeScript ecosystem
      typescript:
        patterns:
          - 'typescript'
          - '@types/*'
          - 'tsx'
          - 'ts-node'
          - 'tsconfig-paths'

      # React ecosystem
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'

      # Vite and build tools
      vite:
        patterns:
          - 'vite'
          - '@vitejs/*'
          - 'lightningcss'

      # Tanstack ecosystem (Router + Query)
      tanstack:
        patterns:
          - '@tanstack/*'

      # Express and backend
      express:
        patterns:
          - 'express'
          - '@types/express'
          - 'body-parser'
          - '@types/body-parser'
          - 'cookie-parser'
          - '@types/cookie-parser'
          - 'helmet'
          - 'cors'
          - '@types/cors'

      # Better Auth
      authentication:
        patterns:
          - 'better-auth'

      # Database and ORM
      database:
        patterns:
          - 'drizzle-orm'
          - 'drizzle-kit'
          - 'better-sqlite3'
          - '@types/better-sqlite3'

      # Forms and validation
      validation:
        patterns:
          - 'react-hook-form'
          - '@hookform/resolvers'
          - 'zod'
          - 'neverthrow'

      # UI and styling
      ui:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
          - 'tailwind-merge'
          - 'class-variance-authority'
          - 'clsx'

      # HTTP client
      http:
        patterns:
          - 'axios'

      # Notifications and UI feedback
      notifications:
        patterns:
          - 'react-hot-toast'
          - 'sonner'

      # Code quality and linting
      code-quality:
        patterns:
          - 'eslint*'
          - '@eslint/*'
          - 'eslint-config-*'
          - 'eslint-plugin-*'
          - 'prettier'
          - 'globals'
          - 'jiti'

      # Node.js types and utilities
      node:
        patterns:
          - '@types/node'
          - 'dotenv'
