name: '🔧 Build & Lint'

on:
  workflow_call:
    inputs:
      ref:
        description: 'Git reference to checkout'
        required: false
        type: string
        default: ${{ github.sha }}
      concurrency-group:
        description: 'Concurrency group for this workflow'
        required: false
        type: string

concurrency:
  group: ${{ inputs.concurrency-group || github.run_id }}
  cancel-in-progress: ${{ inputs.concurrency-group != '' }}

permissions:
  contents: read

jobs:
  build-lint:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || github.sha }}
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: pnpm format:check

      - name: Type check
        run: pnpm type-check

      - name: Run lint
        run: pnpm lint

      - name: Build project
        run: pnpm build
